Race.create(name: "April Fools Half Marathon", distance: "13.1 miles", location: "Atlantic City, NJ", date: DateTime.new(2020,4,25), age_group: "16+")
Race.create(name: "Race to bRUNch", distance: "5 miles", location: "Montclair, NJ", date: DateTime.new(2020,4,26), age_group: "21+")
Race.create(name: "XC Summer Series", distance: "8K", location: "Parsippany, NJ", date: DateTime.new(2020,5,1), age_group: "8+")
Race.create(name: "Run for the Animals", distance: "5K", location: "Brigantine, NJ", date: DateTime.new(2020,5,22), age_group: "12+")
Race.create(name: "Run the Vineyards", distance: "10K", location: "Stockton, NJ", date: DateTime.new(2020,5,22), age_group: "21+")
Race.create(name: "Relay for Life", distance: "5K", location: "Middletown, NJ", date: DateTime.new(2020,5,29), age_group: "8+")
Race.create(name: "Scott Coffee Rotary", distance: "8K", location: "Moorestown, NJ", date: DateTime.new(2020,5,30), age_group: "10+")
Race.create(name: "5k for Kids", distance: "5K", location: "Camden, NJ", date: DateTime.new(2020,6,12), age_group: "6-14")
Race.create(name: "Seashore Gardens", distance: "7K", location: "Atlantic City, NJ", date: DateTime.new(2020,6,12), age_group: "14+")
Race.create(name: "The Racefaster Half Marathon", distance: "13.1 miles", location: "Paramus, NJ", date: DateTime.new(2020,9,12), age_group: "18+")
Race.create(name: "Jersey Shore Half Marathon", distance: "13.1 miles", location: "Highlands, NJ", date: DateTime.new(2020,10,3), age_group: "16+")
Race.create(name: "Novo Nordisk NJ Marathon", distance: "26.2 miles", location: "Long Branch, NJ", date: DateTime.new(2020,10,16), age_group: "18+")
Race.create(name: "Marine Corps Marathon", distance: "26.2 miles", location: "Arlington, VA", date: DateTime.new(2019,10,27), age_group: "18+")
Race.create(name: "NYC Marathon", distance: "26.2 miles", location: "New York, NY", date: DateTime.new(2017,11,4), age_group: "18+")
Race.create(name: "Garden State 10", distance: "10 miles", location: "Somerset, NJ", date: DateTime.new(2020,11,7), age_group: "14+")
Race.create(name: "Princeton Half Marathon", distance: "13.1 miles", location: "Princeton, NJ", date: DateTime.new(2020,11,14), age_group: "16+")
Race.create(name: "Philadelphia Marathon", distance: "13.1 miles", location: "Philadelphia, PA", date: DateTime.new(2016,11,20), age_group: "18+")
Race.create(name: "Patriot Run", distance: "10 miles", location: "Mechanicsburg, PA", date: DateTime.new(2019,4,20), age_group: "12+")
Race.create(name: "Superhero Half Marathon", distance: "13.1 miles", location: "Morristown, NJ", date: DateTime.new(2016,5,15), age_group: "16+")
Race.create(name: "Halloween Half Marathon", distance: "13.1 miles", location: "Morristown, NJ", date: DateTime.new(2016,10,16), age_group: "16+")
Race.create(name: "Rutgers Half Marathon", distance: "13.1 miles", location: "New Brunswick, NJ", date: DateTime.new(2018,4,15), age_group: "14+")
Race.create(name: "Belmar 5", distance: "5 miles", location: "Belmar, NJ", date: DateTime.new(2017,7,9), age_group: "10+")
Race.create(name: "Millie's Pizza Race", distance: "10K", location: "Morristown, NJ", date: DateTime.new(2017,10,1), age_group: "14+")